# Generated by Django 2.2.3 on 2019-08-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='start_date',
        ),
    ]
